# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-30 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=1024, verbose_name='个人形象的URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性'), ('no', '无性')], max_length=8, verbose_name='性别'),
        ),
    ]
